data:
  train_path: /work3/s204138/InferBERT_data/LiverFailure/processed/train.csv
  val_path: /work3/s204138/InferBERT_data/LiverFailure/processed/dev.csv
  test_path: /work3/s204138/InferBERT_data/LiverFailure/processed/test.csv
  feature_path: /work3/s204138/InferBERT_data/LiverFailure/processed/feature.csv
  all_path: /work3/s204138/InferBERT_data/LiverFailure/processed/all.csv
  max_seq_len: 128
  is_lowercase: False # albert-base-v2 is uncased
  pos_weight: 1 # Vector with dimension equal to n_classes that accounts for class imbalances --> vector containing (n_negative / n_positive)

training:
  overwrite: True
  out_dir: experiments/reproduction/outputs/liverfailure
  model_path: experiments/reproduction/outputs/liverfailure/model_weights.pt
  train_results_path: experiments/reproduction/outputs/liverfailure/logs/train_log.json
  val_results_path: experiments/reproduction/outputs/liverfailure/logs/val_log.json
  test_results_path: experiments/reproduction/outputs/liverfailure/logs/test_log.json
  shuffle: True
  start_epoch: 0
  num_workers: 8
  mini_batch_size: 128
  accum_iters: 1 # gradients are accumulated for mini_batch_size * accum_iters before stepping with the optimizer
  use_optimizer: Adam
  print_freq: 75 # print log every x steps
  total_steps: 10000
  warmup_steps: 2000
  optimization:
    Adam:
      name: Adam
      lr: 1.0e-5
      weight_decay: 0.0001
      epsilon: 1.0e-6
      betas:
      - 0.9
      - 0.999 #0.998

    LAMB: 
      name: LAMB
      lr: 0.00176
      weight_decay: 0.0
      epsilon: 1.0e-6
      betas:
      - 0.9
      - 0.999
  validation:
    batch_size: 1
    shuffle: False
causal_inference:
  prediction:
    batch_size: 128
    num_workers: 4
    input_file_path: data/reproduction/Analgesics-induced acute liver failure/processed/all.csv
    output_file_path: experiments/reproduction/outputs/liverfailure/probability_file.csv
    uncertainty_file_path: experiments/reproduction/outputs/liverfailure/uncertainty_file.csv
    uncertainty_est:
      T: 100 # number of samples to draw for each datapoint when estimating mean and var

  analysis:
    probability_file_path: experiments/reproduction/outputs/liverfailure/probability_file.csv
    feature_file_path: data/reproduction/Analgesics-induced acute liver failure/processed/feature.csv
    output_dir: experiments/reproduction/outputs/liverfailure/causality_output

model:
  model_version: albert-base-v2
  pretrained_ckpt: 'experiments/reproduction/outputs/liverfailure/model_weights.pt' # leave blank if training is from scratch
  hidden_size: 768 # hidden dimension, default=768 for base-v2
  intermediate_size: 3072 # dimension in FFN of encoder block, default=3072 for base-v2
  n_attention_heads: 12
  n_memory_blocks: 0
  n_classes: 1 # positive/negative but dim 1 is needed for the loss function
  fc_dropout_prob: 0.2 # dropout at classification head
  attention_dropout_prob: 0.0 # dropout at MHA, default=0.0
  hidden_dropout_prob: 0.0 # dropout at FFN in encoder block, default=0.0