data:
  tramadol:
    dir: 'data/Tramadol'
    feature_path: 'data/Tramadol/processed/feature.csv'
    all_path: 'data/Tramadol/processed/all.csv'
  liverfailure:
    dir: 'data/LiverFailure'
    feature_path: 'data/LiverFailure/processed/feature.csv'
    all_path: 'data/LiverFailure/processed/all.csv'

analysis:
  dataset_name: liverfailure
  # tramadol_columns: ['age', 'gender', 'ade', 'indication', 'psd']
  tramadol_columns: ['age', 'gender', 'dose', 'ade', 'indication', 'psd']
  liverfailure_columns: ['age', 'gender', 'dose', 'outcome', 'indication', 'psd']
  methods:
    PRR:
      threshold_col: PRR
      threshold_value: 2
    MGPS:
      threshold_col: LowerBound
      threshold_value: 2
    ROR:
      threshold_col: ROR
      threshold_value: 2